version: 1.0.{build}
branches:
  only:
    - dev

skip_tags: true

skip_commits:
  files:
    - '.github/**'
    - '**.md'
    - 'scripts/*'

image: Visual Studio 2019

install:
  - git submodule update --init --depth 1

platform: x64

configuration: ReleaseLTCG

build:
  parallel: true
  project: duckstation.sln

after_build:
  - |-
      7z a  duckstation-windows-x64-release.zip .\bin\x64\* -r "-xr!*.pdb" "-xr!common-tests*"
      7z rn duckstation-windows-x64-release.zip updater-x64-ReleaseLTCG.exe updater.exe

test: off

artifacts:
  - path: duckstation-windows-x64-release.zip
