name: Linux Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Install packages
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get -y install libsdl2-dev libgtk2.0-dev

    - name: Compile debug build
      shell: bash
      run: |
        mkdir build-debug
        cd build-debug
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        make
        
    - name: Compile release build
      shell: bash
      run: |
        mkdir build-release
        cd build-release
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make

