name: Create rolling release

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'appveyor.yml'
      - 'scripts/*'
      - '.github/ISSUE_TEMPLATE/*'
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - '**.md'
      - 'appveyor.yml'
      - 'scripts/*'
      - '.github/ISSUE_TEMPLATE/*'
  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0
        submodules: true

    - name: Tag as preview build
      if: github.ref == 'refs/heads/master'
      shell: cmd
      run: |
        echo #pragma once > src/scmversion/tag.h
        echo #define SCM_RELEASE_ASSET "duckstation-windows-x64-release.zip" >> src/scmversion/tag.h
        echo #define SCM_RELEASE_TAGS {"latest", "preview"} >> src/scmversion/tag.h
        echo #define SCM_RELEASE_TAG "preview" >> src/scmversion/tag.h


    - name: Tag as dev build
      if: github.ref == 'refs/heads/dev'
      shell: cmd
      run: |
        echo #pragma once > src/scmversion/tag.h
        echo #define SCM_RELEASE_ASSET "duckstation-windows-x64-release.zip" >> src/scmversion/tag.h
        echo #define SCM_RELEASE_TAGS {"latest", "preview"} >> src/scmversion/tag.h
        echo #define SCM_RELEASE_TAG "latest" >> src/scmversion/tag.h


    - name: Compile x64 release build
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        msbuild duckstation.sln -t:Build -p:Platform=x64;Configuration=ReleaseLTCG

    - name: Create x64 symbols archive
      shell: cmd
      run: |
        "C:\Program Files\7-Zip\7z.exe" a -r duckstation-windows-x64-release-symbols.zip ./bin/x64/*.pdb

    - name: Upload x64 release symbols artifact
      uses: actions/upload-artifact@v1
      with:
        name: "windows"
        path: "duckstation-windows-x64-release-symbols.zip"

    - name: Remove extra bloat before archiving
      shell: cmd
      run: |
        del /Q bin\x64\*.pdb
        del /Q bin\x64\*.exp
        del /Q bin\x64\*.lib
        del /Q bin\x64\*.iobj
        del /Q bin\x64\*.ipdb
        del /Q bin\x64\common-tests*
        rename bin\x64\updater-x64-ReleaseLTCG.exe updater.exe

    - name: Create x64 release archive
      shell: cmd
      run: |
        "C:\Program Files\7-Zip\7z.exe" a -r duckstation-windows-x64-release.zip ./bin/x64/*

    - name: Upload x64 release artifact
      uses: actions/upload-artifact@v1
      with:
        name: "windows"
        path: "duckstation-windows-x64-release.zip"


  windows-arm64-build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0
        submodules: true

    - name: Tag as preview build
      if: github.ref == 'refs/heads/master'
      shell: cmd
      run: |
        echo #pragma once > src/scmversion/tag.h
        echo #define SCM_RELEASE_ASSET "duckstation-windows-x64-release.zip" >> src/scmversion/tag.h
        echo #define SCM_RELEASE_TAGS {"latest", "preview"} >> src/scmversion/tag.h
        echo #define SCM_RELEASE_TAG "preview" >> src/scmversion/tag.h


    - name: Tag as dev build
      if: github.ref == 'refs/heads/dev'
      shell: cmd
      run: |
        echo #pragma once > src/scmversion/tag.h
        echo #define SCM_RELEASE_ASSET "duckstation-windows-x64-release.zip" >> src/scmversion/tag.h
        echo #define SCM_RELEASE_TAGS {"latest", "preview"} >> src/scmversion/tag.h
        echo #define SCM_RELEASE_TAG "latest" >> src/scmversion/tag.h


    - name: Compile arm64 release build
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64_arm64
        msbuild duckstation.sln -t:Build -p:Platform=ARM64;Configuration=ReleaseLTCG

    - name: Create arm64 symbols archive
      shell: cmd
      run: |
        "C:\Program Files\7-Zip\7z.exe" a -r duckstation-windows-arm64-release-symbols.zip ./bin/ARM64/*.pdb

    - name: Upload arm64 release symbols artifact
      uses: actions/upload-artifact@v1
      with:
        name: "windows-arm64"
        path: "duckstation-windows-arm64-release-symbols.zip"

    - name: Remove extra bloat before archiving
      shell: cmd
      run: |
        del /Q bin\ARM64\*.pdb
        del /Q bin\ARM64\*.exp
        del /Q bin\ARM64\*.lib
        del /Q bin\ARM64\*.iobj
        del /Q bin\ARM64\*.ipdb
        del /Q bin\ARM64\common-tests*
        rename bin\ARM64\updater-ARM64-ReleaseLTCG.exe updater.exe
                
    - name: Create arm64 release archive
      shell: cmd
      run: |
        "C:\Program Files\7-Zip\7z.exe" a -r duckstation-windows-arm64-release.zip ./bin/ARM64/*

    - name: Upload arm64 release artifact
      uses: actions/upload-artifact@v1
      with:
        name: "windows-arm64"
        path: "duckstation-windows-arm64-release.zip"


  linux-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0

    - name: Install packages
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get -y install cmake ninja-build ccache libsdl2-dev libgtk-3-dev qtbase5-dev qtbase5-dev-tools qtbase5-private-dev qt5-default qttools5-dev

    - name: Compile build
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SDL_FRONTEND=ON -DBUILD_QT_FRONTEND=ON -DUSE_SDL2=ON -G Ninja ..
        ninja
        ../appimage/generate_appimages.sh $(pwd)

    - name: Upload SDL AppImage
      uses: actions/upload-artifact@v1
      with:
        name: "linux-x64-appimage-sdl"
        path: "build/duckstation-sdl-x64.AppImage"

    - name: Upload SDL AppImage zsync
      uses: actions/upload-artifact@v1
      with:
        name: "linux-x64-appimage-sdl-zsync"
        path: "build/duckstation-sdl-x64.AppImage.zsync"

    - name: Upload Qt AppImage
      uses: actions/upload-artifact@v1
      with:
        name: "linux-x64-appimage-qt"
        path: "build/duckstation-qt-x64.AppImage"

    - name: Upload Qt AppImage zsync
      uses: actions/upload-artifact@v1
      with:
        name: "linux-x64-appimage-qt-zsync"
        path: "build/duckstation-qt-x64.AppImage.zsync"


  android-build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0

    - name: Compile with Gradle
      shell: bash
      run: |
        cd android
        ./gradlew assembleRelease

    - name: Sign APK
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: android/app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.APK_SIGNING_KEY }}
        alias: ${{ secrets.APK_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.APK_KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.APK_KEY_PASSWORD }}

    - name: Rename APK
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
      shell: bash
      run: |
        cd android
        mv app/build/outputs/apk/release/app-release-unsigned-signed.apk ../duckstation-android.apk
         
    - name: Upload APK
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
      uses: actions/upload-artifact@v1
      with:
        name: "android"
        path: "duckstation-android.apk"

  macos-build:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0

    - name: Install packages
      shell: bash
      run: |
        brew install qt5 sdl2

    - name: Clone mac externals
      shell: bash
      run: |
        git clone https://github.com/stenzek/duckstation-ext-mac.git dep/mac

    - name: Compile and zip .app
      shell: bash
      run: |
        mkdir build
        cd build
        export MACOSX_DEPLOYMENT_TARGET=10.14
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SDL_FRONTEND=OFF -DBUILD_QT_FRONTEND=ON -DUSE_SDL2=ON -DQt5_DIR=/usr/local/opt/qt/lib/cmake/Qt5 ..
        cmake --build . --parallel 2
        cd bin
        zip -r duckstation-mac-release.zip DuckStation.app/

    - name: Upload macOS .app
      uses: actions/upload-artifact@v1
      with:
        name: "macos-x64"
        path: "build/bin/duckstation-mac-release.zip"


  create-release:
    needs: [windows-build, windows-arm64-build, linux-build, android-build, macos-build]
    runs-on: "ubuntu-latest"
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    steps:
      - name: Download Windows Artifacts
        uses: actions/download-artifact@v1
        with:
          name: "windows"

      - name: Download Windows ARM64 Artifact
        uses: actions/download-artifact@v1
        with:
          name: "windows-arm64"

      - name: Download SDL AppImage Artifact
        uses: actions/download-artifact@v1
        with:
          name: "linux-x64-appimage-sdl"

      - name: Download SDL AppImage zsync Artifact
        uses: actions/download-artifact@v1
        with:
          name: "linux-x64-appimage-sdl-zsync"

      - name: Download Qt AppImage Artifact
        uses: actions/download-artifact@v1
        with:
          name: "linux-x64-appimage-qt"

      - name: Download Qt AppImage zsync Artifact
        uses: actions/download-artifact@v1
        with:
          name: "linux-x64-appimage-qt-zsync"

      - name: Download Android APK
        uses: actions/download-artifact@v1
        with:
          name: "android"

      - name: Download Mac App
        uses: actions/download-artifact@v1
        with:
          name: "macos-x64"

      - name: Create preview release
        if: github.ref == 'refs/heads/master'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "preview"
          prerelease: true
          title: "Latest Preview Build"
          files: |
            windows/duckstation-windows-x64-release.zip
            windows/duckstation-windows-x64-release-symbols.zip
            windows-arm64/duckstation-windows-arm64-release.zip
            windows-arm64/duckstation-windows-arm64-release-symbols.zip
            linux-x64-appimage-sdl/duckstation-sdl-x64.AppImage
            linux-x64-appimage-sdl-zsync/duckstation-sdl-x64.AppImage.zsync
            linux-x64-appimage-qt/duckstation-qt-x64.AppImage
            linux-x64-appimage-qt-zsync/duckstation-qt-x64.AppImage.zsync
            android/duckstation-android.apk

      - name: Create dev release
        if: github.ref == 'refs/heads/dev'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Development Build"
          files: |
            windows/duckstation-windows-x64-release.zip
            windows/duckstation-windows-x64-release-symbols.zip
            windows-arm64/duckstation-windows-arm64-release.zip
            windows-arm64/duckstation-windows-arm64-release-symbols.zip
            linux-x64-appimage-sdl/duckstation-sdl-x64.AppImage
            linux-x64-appimage-sdl-zsync/duckstation-sdl-x64.AppImage.zsync
            linux-x64-appimage-qt/duckstation-qt-x64.AppImage
            linux-x64-appimage-qt-zsync/duckstation-qt-x64.AppImage.zsync
            android/duckstation-android.apk
            macos-x64/duckstation-mac-release.zip

