name: Windows Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Compile release build
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        msbuild duckstation.sln -t:Build -p:Platform=x64;Configuration=ReleaseLTCG
        
    - name: Remove extra bloat before archiving
      shell: cmd
      run: |
        del /Q bin\x64\*.pdb
        del /Q bin\x64\*.exp
        del /Q bin\x64\*.lib
        del /Q bin\x64\*.iobj
        del /Q bin\x64\*.ipdb

    - name: Upload release archive
      uses: actions/upload-artifact@v1
      with:
        name: "duckstation-windows-x64-release"
        path: ".\\bin\\x64"
